require:
  - rubocop
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'bin/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'app/views/posts/rss.builder'
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 130

Metrics/ModuleLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/StringConcatenation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/NumericPredicate:
  EnforcedStyle: comparison

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: space

Layout/EndAlignment:
  EnforcedStyleAlignWith: keyword

Layout/ClassStructure:
  Enabled: true

Layout/MultilineArrayLineBreaks:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true