version: '3.4'

services:
#  redis:
#    image: "redis:7-alpine"
#    ports:
#      - 6379
#    volumes:
#      - ./tmp/redis_data:/var/lib/redis/data

  db:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    env_file: 
      - .env
    volumes:
      - .db-data:/var/lib/postgresql/pgdata

  twilight:
    #build: .
    image: twilight:latest
    container_name: twilight
    restart: on-failure
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    # Traefik example
#    labels:
#      - "traefik.enable=true"
#      - "traefik.port=${PORT}"

#      - "traefik.http.services.twilight.loadbalancer.server.port=${PORT}"
#      - "traefik.http.routers.twilight.rule=Host(`twilight.example.com`)" # change this
#      - "traefik.http.routers.twilight.entrypoints=http"
#      - "traefik.http.routers.twilight.middlewares=twilight-secure-redirect"

#      - "traefik.http.middlewares.twilight-secure-redirect.redirectscheme.scheme=https"

#      - "traefik.http.routers.twilight-secure.rule=Host(`twilight.example.com`)" # change this
#      - "traefik.http.routers.twilight-secure.entrypoints=https"
#      - "traefik.http.routers.twilight-secure.tls=true"
    depends_on:
      - db
#      - redis
    links:
      - db:db
    volumes:
      - .:/root/app/
    tty: true
    stdin_open: true

volumes:
  db-data:
    external: false