version: '3.4'

services:
#  redis:
#    image: "redis:7-alpine"
#    ports:
#      - 6379
#    volumes:
#      - ./tmp/redis_data:/var/lib/redis/data

  db:
    image: postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    env_file: 
      - .env
    volumes:
      - .db-data:/var/lib/postgresql/pgdata

  web:
    build: .
    #command: > 
    #    /bin/bash -c
    #    "rm -f /tmp/server.pid
    #    && bin/rails db:create
    #    && rails db:migrate
    #    && bundle exec rake assets:precompile
    #    && bundle exec rails server -e ${ENV} -b 0.0.0.0 -p ${PORT} -P /tmp/server.pid"
    ports:
      - "${PORT}:${PORT}"
    env_file: .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - PORT=${PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
#      - redis
    links:
      - db:db
    volumes:
      - .:/home/app
    tty: true
    stdin_open: true

volumes:
  db-data:
    external: false