development:
  adapter: redis
  url: <%= Rails.configuration.credentials[:redis][:url] %>
  channel_prefix: Twilight_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.configuration.credentials[:redis][:url] %>
  channel_prefix: Twilight_production
