development:
  adapter: redis
  url: <%= Rails.configuration.credentials&.dig(:redis, :url) { "redis://localhost:6379/1" } %>
  channel_prefix: Twilight_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= Rails.configuration.credentials&.dig(:redis, :url) { "redis://localhost:6379/1" } %>
  channel_prefix: Twilight_production
