development:
  host: 'localhost'
  port: 3080
  rollbar:
    enabled: false
    auth_token: ""
  telegram:
    token: 1234567890:ABCDEFGHIGKLMNOPQ-RSTUVWXYZ12345678
    author: 1234567890 # Author ID
    channel_ids: ["1234567890"] # Tg channels
    reg_notify: true # Send message about user registration

production:
  host: 'localhost'
  port: 3080
  rollbar:
    enabled: false
    auth_token: ""
  telegram:
    token: 1234567890:ABCDEFGHIGKLMNOPQ-RSTUVWXYZ12345678
    author: 1234567890 # Author ID
    channel_ids: ["1234567890"] # Tg channels
    reg_notify: true # Send message about user registration