development:
  host: 'localhost'
  port: 3080
  locale: :en # Also supports :ru
  time_zone: 'Europe/Moscow' # 'UTC'
  title: Twilight # title in header
  rss_description: Description
  rss_default_visible_posts: 30
  rss_max_visible_posts: 50
  max_upload_files: 10
  max_file_size: 10
  invite_codes_register_only: false
  rollbar:
    enabled: false
    auth_token: ""
  fail2ban: # Ban IP for bypass rss token
    enabled: false
  links: # Empty strings not shown on main page
    github: "https://github.com/whiletruedoend"
    mal: ""
    kinopoisk: ""
    telegram: "https://example.com"
    matrix: ""
    jabber: "xmpp:example@jab.ber"


production:
  host: 'localhost'
  port: 3080
  locale: :en # Also supports :ru
  time_zone: 'Europe/Moscow' # 'UTC'
  title: Twilight # title in header
  rss_description: Description
  rss_default_visible_posts: 30
  rss_max_visible_posts: 50
  max_upload_files: 10
  max_file_size: 10
  invite_codes_register_only: false
  rollbar:
    enabled: false
    auth_token: ""
  fail2ban: # Ban IP for bypass rss token
    enabled: false
  links: # Empty strings not shown on main page
    github: "https://github.com/whiletruedoend"
    mal: ""
    kinopoisk: ""
    telegram: "https://example.com"
    matrix: ""
    jabber: "xmpp:example@jab.ber"