development:
  host: 'localhost'
  port: 3080
  rollbar:
    enabled: false
    auth_token: ""
  telegram:
    token: 1234567890:ABCDEFGHIGKLMNOPQ-RSTUVWXYZ12345678
    author: 1234567890 # Author ID
    channel_ids: ["1234567890"] # Tg channels
    attachment_channel_id: "-1234567890123" # Bot send images to channel and send file_id to other channels (anti-reupload)
    reg_notify: false # Send message about user registration
  matrix:
    enabled: false
    server: "https://matrix.org/_matrix/"
    access_token: "...ABCDEFGHIJKLMNOPQRSTUVWXYZ...."
    room_ids: ["!abcdefghijklmnopqr:matrix.org"]
  fail2ban: # Ban IP for bypass rss token
    enabled: false
  links: # Empty strings not shown on main page
    github: "https://github.com/whiletruedoend"
    mal: ""
    kinopoisk: ""
    telegram: "https://example.com"
    matrix: ""
    jabber: "xmpp:example@jab.ber"


production:
  host: 'localhost'
  port: 3080
  rollbar:
    enabled: false
    auth_token: ""
  telegram:
    token: 1234567890:ABCDEFGHIGKLMNOPQ-RSTUVWXYZ12345678
    author: 1234567890 # Author ID
    channel_ids: ["1234567890"] # Tg channels
    attachment_channel_id: "-1234567890123" # Bot send images to channel and send file_id to other channels (anti-reupload)
    reg_notify: false # Send message about user registration
  matrix:
    enabled: false
    server: "https://matrix.org/_matrix/"
    access_token: "...ABCDEFGHIJKLMNOPQRSTUVWXYZ...."
    room_ids: ["!abcdefghijklmnopqr:matrix.org"]
  fail2ban: # Ban IP for bypass rss token
    enabled: false
  links: # Empty strings not shown on main page
    github: "https://github.com/whiletruedoend"
    mal: ""
    kinopoisk: ""
    telegram: "https://example.com"
    matrix: ""
    jabber: "xmpp:example@jab.ber"