development:
  host: 'localhost'
  port: 3080
  locale: :en # Also supports :ru
  time_zone: 'Europe/Moscow' # 'UTC'
  title: Twilight # title in header
  root_page: 1 # 0 - special text page, 1 - posts page, 2 - feed page
  rss_description: Description
  rss_default_visible_posts: 30
  rss_max_visible_posts: 50
  max_upload_files: 10
  max_file_size: 10
  invite_codes_register_only: false
  enable_categories: true
  rollbar:
    enabled: false
    auth_token: ""
  fail2ban: # Ban IP for bypass rss token
    enabled: false
  links: # Empty strings not shown on main page
    github: "https://github.com/whiletruedoend"
    mal: ""
    kinopoisk: ""
    telegram: "https://example.com"
    matrix: ""
    jabber: "xmpp:example@jab.ber"

production:
  host: 'localhost'
  port: 3080
  locale: :en # Also supports :ru
  time_zone: 'Europe/Moscow' # 'UTC'
  title: Twilight # title in header
  root_page: 1 # 0 - special text page, 1 - posts page, 2 - feed page
  rss_description: Description
  rss_default_visible_posts: 30
  rss_max_visible_posts: 50
  max_upload_files: 10
  max_file_size: 10
  invite_codes_register_only: false
  enable_categories: true
  rollbar:
    enabled: false
    auth_token: ""
  fail2ban: # Ban IP for bypass rss token
    enabled: false
  links: # Empty strings not shown on main page
    github: "https://github.com/whiletruedoend"
    mal: ""
    kinopoisk: ""
    telegram: "https://example.com"
    matrix: ""
    jabber: "xmpp:example@jab.ber"
  # PASTE YOUR KEY BELOW! Use: rails secret OR type in rails console: SecureRandom.hex(64)
  secret_key_base: 019d6b8b68cee638184885b4319cd5135a2f448305f5309945476300020003169331ccdd644e4c239a126efe6510a424e4c12543609f2643607334719894ea30 

test:
  locale: :en # Also supports :ru
  time_zone: 'Europe/Moscow' # 'UTC'
  rss_default_visible_posts: 30
  rss_max_visible_posts: 50
  max_upload_files: 10
  max_file_size: 10
  invite_codes_register_only: false
  enable_categories: true
  rollbar:
    enabled: false
    auth_token: ""