development:
  host: '0.0.0.0'
  port: 3080
  locale: :en # Also supports :ru
  time_zone: 'Europe/Moscow' # 'UTC'
  title: Twilight # title in header
  root_page: 1 # 0 - special text page, 1 - posts page, 2 - feed page
  need_auth: false # Need auth for view all posts page?
  rss_description: Description
  rss_default_visible_posts: 30
  rss_max_visible_posts: 50
  max_upload_files: 10
  max_file_size: 10
  invite_codes_register_only: false
  enable_categories: true
  redis:
    # set 'false' if you already have working redis server, or want
    # launch him manually with command: redis-server
    autostart: true
    url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  rollbar:
    enabled: false
    auth_token: ""
  fail2ban: # Ban IP for bypass rss token
    enabled: false
  links: # Empty strings not shown on main page
    github: "https://github.com/whiletruedoend"
    mal: ""
    kinopoisk: ""
    telegram: "https://example.com"
    matrix: ""
    jabber: "xmpp:example@jab.ber"
  socks_proxy:
    socks_proxy_enabled: false
    socks_server: "127.0.0.1"
    socks_port: 9050
    socks_username: null
    socks_password: null


production:
  host: '0.0.0.0'
  port: 3080
  locale: :en # Also supports :ru
  time_zone: 'Europe/Moscow' # 'UTC'
  title: Twilight # title in header
  root_page: 1 # 0 - special text page, 1 - posts page, 2 - feed page
  need_auth: false # Need auth for view all posts page?
  rss_description: Description
  rss_default_visible_posts: 30
  rss_max_visible_posts: 50
  max_upload_files: 10
  max_file_size: 10
  invite_codes_register_only: false
  enable_categories: true
  redis:
    # set 'false' if you already have working redis server, or want
    # launch him manually with command: redis-server
    autostart: true
    url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  rollbar:
    enabled: false
    auth_token: ""
  fail2ban: # Ban IP for bypass rss token
    enabled: false
  links: # Empty strings not shown on main page
    github: "https://github.com/whiletruedoend"
    mal: ""
    kinopoisk: ""
    telegram: "https://example.com"
    matrix: ""
    jabber: "xmpp:example@jab.ber"
  socks_proxy:
    socks_proxy_enabled: false
    socks_server: "127.0.0.1"
    socks_port: 9050
    socks_username: null
    socks_password: null
  # PASTE YOUR KEY BELOW! Use: rails secret OR type in rails console: SecureRandom.hex(64)
  secret_key_base: 019d6b8b68cee638184885b4319cd5135a2f448305f5309945476300020003169331ccdd644e4c239a126efe6510a424e4c12543609f2643607334719894ea30 

test:
  locale: :en
  time_zone: 'Europe/Moscow'
  rss_default_visible_posts: 30
  rss_max_visible_posts: 50
  max_upload_files: 10
  max_file_size: 10
  invite_codes_register_only: false
  enable_categories: true