development:
  host: 'localhost'
  port: 3080
  rollbar:
    enabled: false
    auth_token: ""
  telegram:
    token: 1234567890:ABCDEFGHIGKLMNOPQ-RSTUVWXYZ12345678
    author: 1234567890 # Author ID
    channel_ids: ["1234567890"] # Tg channels
    attachment_channel_id: "-1234567890123" # Bot send images to channel and send file_id to other channels (anti-reupload)
    reg_notify: true # Send message about user registration
  fail2ban: # Ban IP for bypass rss token
    enabled: false

production:
  host: 'localhost'
  port: 3080
  rollbar:
    enabled: false
    auth_token: ""
  telegram:
    token: 1234567890:ABCDEFGHIGKLMNOPQ-RSTUVWXYZ12345678
    author: 1234567890 # Author ID
    channel_ids: ["1234567890"] # Tg channels
    attachment_channel_id: "-1234567890123" # Bot send images to channel and send file_id to other channels (anti-reupload)
    reg_notify: true # Send message about user registration
  fail2ban: # Ban IP for bypass rss token
    enabled: false