# config/database.yml
default: &default
  adapter: postgresql # sqlite3
  encoding: unicode
  host: localhost
  port: 5432
  username: twilight
  password: pass
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: twilight_dev # db/development.sqlite3

test:
  <<: *default
  database: twilight_test # db/test.sqlite3

production:
  <<: *default
  database: twilight_production # db/production.sqlite3