# Sqlite 3
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
development:
  <<: *default
  database: db/development.sqlite3
test:
  <<: *default
  database: db/test.sqlite3
production:
  <<: *default
  database: db/production.sqlite3

# Postgres
#development:
#  adapter: postgresql
#  host: localhost
#  port: 5432
#  username: twilight
#  password: pass
#  database: twilight
#  encoding: unicode
#  pool: 10
#  timeout: 5000

#production:
#  adapter: postgresql
#  host: localhost
#  port: 5432
#  username: twilight
#  password: pass
#  database: twilight
#  encoding: unicode
#  pool: 10
#  timeout: 5000
