# config/database.yml
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] { localhost } %>
  port: <%= ENV['POSTGRES_PORT'] { 5432 } %>
  username: <%= ENV['POSTGRES_USER'] { twilight } %>
  password: <%= ENV['POSTGRES_PASSWORD'] { password } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] { twilight_development } %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] { twilight_production } %>

test:
  <<: *default
  database: twilight_test