# config/database.yml
default: &default
  adapter: postgresql # sqlite3
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] { localhost } %>
  port: <%= ENV['POSTGRES_PORT'] { 5432 } %>
  username: <%= ENV['POSTGRES_USER'] { twilight } %>
  password: <%= ENV['POSTGRES_PASSWORD'] { password } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] { twilight_development } %>
  # database: db/development.sqlite3 # For sqlite3

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] { twilight_production } %>
  # database: db/production.sqlite3 # For sqlite3

test:
  adapter: sqlite3
  encoding: unicode
  database: db/twilight_test.sqtile3